### PR TITLE
Add entry for hexdump: unmaintainted

### PR DESCRIPTION
**Pull request by asomers**

### CODE REVIEW

**Comment by tbu-** [comment]
https://github.com/tbu-/hexdump/issues/2#issuecomment-2132384446

**Comment by alex** [comment]
Please see our guidance on handling unmaintained crates: https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md

I'm going to add some additional language reminding folks not to be rude or aggressive with maintainers, it's not an acceptable way to conduct oneself in open source.

**Comment by tarcieri** [comment]
> Oh, you gave me a whole 13 minutes to respond.

@tbu- FWIW, the stated time period in the policy @alex linked is 90 days before an advisory is filed.

This is definitely too early.

**Comment by asomers** [comment]
Oh sorry @alex .  I didn't see that HOWTO.  I based this PR on RUSTSEC-2021-0139 for ansi_term, which was filed on the same day as the linked github issue.

**Pull request closed without merging**
