### PR TITLE
Add advisory for rusqlite

### PR DESCRIPTION
**Pull request by thomcc**
For work I completed an audit of rusqlite's unsafe code. There were a number of issues for various issues, most of them in uncommonly used APIs, but they could be fairly severe nonetheless.

I'd... prefer not to split this out among N separate advisories. Mostly because I'm lazy, but I also don't really see the benefit it would give. (Aside from making the `description` better, I guess)

Note that while VTab/VTabCursor not being unsafe traits isn't listed in the `functions`, you need to use `create_module` in order to expose that so it should be fine.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Seeing that there is no semver-compatible fixed version, it would be nice to also specify in which version every issue was introduced. However, seeing that there's a lot of them and you need to opt in to extra features to get to the problematic code, it might not be worth the trouble.

**Comment by thomcc** [comment]
Okay, I’ll take a look.

**Comment by tarcieri** [comment]
Will go ahead and merge this. Please open a separate PR if you'd like to add info about which versions were unaffected.

**Comment by tarcieri** [comment]
Assigned `RUSTSEC-2020-0014` in #274

**Pull request merged**
