### PR TITLE
Create advisory for difference

### LINKED ISSUE #534: difference crate not maintained anymore
https://github.com/johannhof/difference.rs/issues/45

It's been about 4 months since this issue was submitted with no response yet.

### PR DESCRIPTION
**Pull request by brightly-salty**
Fixes #534

### CODE REVIEW

**Comment by Shnatsel** [comment]
Thank you!

**Comment by Shnatsel** [comment]
Also, apologies for the late response.

**Comment by mx00s** [comment]
Thank you. I received a notification about this.

One of the suggested alternatives, `pretty_assertions`, actually depends on `difference`.

**Comment by Shnatsel** [comment]
Thanks for pointing that out! I'll remove `pretty_assertions` from suggested alternatives.

**Comment by mitsuhiko** [comment]
I wasn't able to get any of the recommended replacements to work in my setup in insta. As a result I started writing a replacement that is closer to `difference` without inheriting its flaws. If anyone is also running into that I would be curious to get feedback: https://crates.io/crates/similar

**Comment by Shnatsel** [comment]
@mitsuhiko once you feel it's OK for wider usage, you're welcome to add it to the list of alternatives on this advisory.

**Pull request merged**
