### PR TITLE
Report unsoundness in Solana/spl-token-swap

### PR DESCRIPTION
**Pull request by shinmao**

### CODE REVIEW

**Review by kornelski — APPROVED** [review]

**Comment by kornelski** [comment]
There's no patched version, but the project looks unmaintained.

**Comment by shinmao** [comment]
@kornelski yes. The crate doesn't announce to be unmaintained, but it isn't updated over 2 years. Do you think we should release unmaintained advisories?

**Comment by kornelski** [comment]
Before making unmaintained advisories, ask crate maintainers to confirm it. The repository seems to be active.

**Comment by shinmao** [comment]
> Before making unmaintained advisories, ask crate maintainers to confirm it. The repository seems to be active.

I think it is still active since there was a commit two months ago.

**Pull request merged**
