### PR TITLE
Missing sanitazion in mozwire allows local file overwrite of files ending in .conf

### PR DESCRIPTION
**Pull request by alexanderkjall**
fix committed but not released yet.

### CODE REVIEW

**Review by Shnatsel — APPROVED** [review]
Thanks for the report! Looks good to me.

@tarcieri do you see any issues with merging advisories before the version mentioned as patched is actually released?

**Comment by alexanderkjall** [comment]
It would maybe be good to add a category for path traversal problems?

**Comment by tarcieri** [comment]
@Shnatsel the only problem is it gives people no recourse as to how to solve the vulnerability, but it wouldn't be the first time.

@alexanderkjall we already have local file disclosure. We could also add unrestricted file upload.

The problem with "path traversal" / "directory traversal" is it's ambiguous as to what capabilities it actually gives the attacker.

(Also this is where we should probably implement CWE, but that's a somewhat nontrivial endeavor)

**Comment by Shnatsel** [comment]
0.4.1 is released, merging.

**Pull request merged**
