### PR TITLE
nanorand `tls_rand` aliased mutable references

### PR DESCRIPTION
**Pull request by Cyborus04**

### CODE REVIEW

**Comment by Shnatsel** [comment]
I've taken the liberty of removing the category that made CI fail and adding a link to the original issue on Github. I'll merge this as soon as CI passes. Thank you!

**Comment by Cyborus04** [comment]
No problem, happy to help!

Is there a list of valid categories somewhere? I tried looking but didn't find anything

**Comment by Shnatsel** [comment]
It's in the README.md:

```
# Optional: Categories this advisory falls under. Valid categories are:
# "code-execution", "crypto-failure", "denial-of-service", "file-disclosure"
# "format-injection", "memory-corruption", "memory-exposure", "privilege-escalation"
categories = ["crypto-failure"]
```

I assume you used some other file as a starting point? I should update that too.

**Comment by Cyborus04** [comment]
Oh, I guess I didn't read that closely enough. I went to the README.md from the contribution guide, then just clicked right through to the example advisory. Whoops!

**Pull request merged**
