### PR TITLE
Add Triage Labels Guide

### PR DESCRIPTION
**Pull request by pinkforest**
Adds guide to use labels for triaging PRs

### CODE REVIEW

**Comment by Shnatsel** [comment]
I am hesitant to add extra steps to an already lengthy process, so let's look at each and see if it solves an actual problem:

- `Unmaintained` - I think the distinction between unmaintained and a vulnerability is already apparent from the title.
- `Unsound` -  Is the distinction between an unsound crate and a vulnerability important enough to surface it in the pull request overview? I cannot think of any reason why I would need this info at a glance in the list, or why I should spend time tagging it.
- `Waiting-*` sounds like useful info to have at a glance. However, is there a mechanism to automatically remove them once the author or the maintainer responds? It sounds like they would get out of date easily, even if manually tagged at the start.
- `Propose-*` - is there an advantage to using labels over communicating this verbally? When I see complex labels of things like CNCF projects, I feel like I'm in the middle of some bysantine process I don't understand, and it makes the project feel less approachable to me, subjectively. Also, only maintainers can edit labels, which creates a perceived power asymmetry.

**Comment by pinkforest** [comment]
It definitely helped myself to pick up things past couple of days when having to catch up where that PR was at.

It also signals everyone very clearly without having to read a lot of text what is going.

It also helps to nudge people - just writing about it doesn't necessarily make it as "official" sounding as a label does.

Comes down to psychology and awareness.

**Comment by Shnatsel** [comment]
Now that they're optional, perhaps move it to the end of the guide?

**Comment by pinkforest** [comment]
Done

**Review by Shnatsel — APPROVED** [review]
SGTM but I'd prefer to hear from another maintainer

**Review by alex — COMMENTED** [review]
LGTM.

Perhaps we could even add a github action to apply the unsound/unmaintained labels automatically

**Pull request merged**
