### PR TITLE
fyrox: double free happens if panic occurs 

### PR DESCRIPTION
**Pull request by kuzeyardabulut**
Original issue report: https://github.com/FyroxEngine/Fyrox/pull/476

### CODE REVIEW

**Comment by Shnatsel** [comment]
Thank you for the report!

Do you know if a published version with the fix is forthcoming in the next few days? It would be better to file an actionable advisory with a fixed version already available.

**Comment by Shnatsel** [comment]
Actually let me ask the maintainers on the original issue

**Comment by adamreichold** [comment]
While using `ManuallyDrop` as done in the pull request is certainly an improvement, `Vec::from_raw_parts` does not panic (it does not even do arithmetic which could panic in debug builds) and hence I don't think there is an actual vulnerability here.

**Comment by Nilstrieb** [comment]
I don't think this needs an advisory. The code was sound as-is, it was purely a refactoring that improved the code and made it nicer and more robust in the future.

**Comment by Shnatsel** [comment]
Closing since this has been shown not to be a security issue in practice. Thank you @adamreichold and @Nilstrieb for the input!

**Pull request closed without merging**
