### PR TITLE
Add advisory for slice-deque

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by tarcieri** [comment]
Thanks for reporting this!

Looks like the build failed because the filename needs to be `RUSTSEC-0000-0000.toml`.

**Comment by gnzlbg** [comment]
Everything green now

**Comment by tarcieri** [comment]
Assigned RUSTSEC-2019-0002 in #96

**Comment by dpc** [comment]
Published in crev https://github.com/dpc/crev-proofs/blob/master/FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE/reviews/2019-05-packages-Ua7DxQ.proof.crev#L1

**Pull request merged**
