### PR TITLE
Add advisory for tower-http#204

### PR DESCRIPTION
**Pull request by davidpdrsn**

### CODE REVIEW

**Comment by Shnatsel** [comment]
Looks good to me, merging. Thanks for the report!

**Comment by Roguelazer** [comment]
this appears to have been made in the wrong year; would it be worth fixing the date to be 2022 instead of 2021?

**Comment by Shnatsel** [comment]
Ah, thanks for catching that! I've opened #1165 to fix that

**Comment by davidpdrsn** [comment]
> this appears to have been made in the wrong year; would it be worth fixing the date to be 2022 instead of 2021?

Ah ups. Sorry about that 😞

**Pull request merged**
