### PR TITLE
Fix escapes in hyper advisory

### LINKED ISSUE #159: hyper/RUSTSEC-2017-0002.toml has unquoted characters
The description contains the text:
> Serializing of headers to the socket did not filter the values for newline bytes (\r or \n),

The `\r` and `\n` are parsed as actual escaped cr/lf, and so the description is printed as:
```
 or alizing of headers to the socket did not filter the values for newline bytes (
),
which allowed for header values to split a request or response. People would not likely include
```

I'm not sure if this intended in the format of `description`, or if this is a bug in the `rustsec` crate. As far as I can tell, it isn't possible to print the description with `cargo audit`, so maybe this has been overlooked.

### PR DESCRIPTION
**Pull request by vks**
Fixes #159.

### CODE REVIEW

**Comment by tarcieri** [comment]
Let's see if that works...

**Comment by tarcieri** [comment]
Well, it's better than it was, but `\r` and `\n` probably need to be escaped with backticks:

https://rustsec.org/advisories/RUSTSEC-2017-0002.html

**Comment by vks** [comment]
I was not sure whether you are performing any markdown processing. Should I add the backticks?

**Comment by tarcieri** [comment]
Yes please, we'll see if that fixes it.

Longer term the web site could probably benefit from a simpler rendering pipeline.

**Pull request merged**
