### PR TITLE
Remove unmaintained status of `markdown`

### PR DESCRIPTION
**Pull request by wooorm**
Related-to: GH-1191.

### CODE REVIEW

**Comment by wooorm** [comment]
lgtm :)

**Comment by pinkforest** [comment]
Thanks for the contribution :partying_face: 

I think we'll just mark from 1.0.0-alpha.1 as resolved so it will note on anything stuck at 0.3.0 so that will incentivise upgrading - widthdrawn wouldn't continue note 0.3.0 users who are using the unmaintained one - lmk if any issues with this - in any case the advisories never really get deleted but marked with these meta tags.

Cheers

**Comment by wooorm** [comment]
oh that sounds better (though I don‘t know much about all these tools!)

**Comment by pinkforest** [comment]
The ones I tend to recommend:
- [cargo deny](https://crates.io/crates/cargo-deny) - for PR's
- [cargo audit](https://crates.io/crates/cargo-audit) - for cron style checks and
- dependabot from GitHub to send PR's for any dep bumps :)

as an example:
- https://github.com/lunatic-solutions/lunatic/blob/main/.github/dependabot.yml
- https://github.com/lunatic-solutions/lunatic/blob/main/.github/workflows/cargo-audit.yml
- https://github.com/lunatic-solutions/lunatic/blob/main/.github/workflows/cargo-deny-pr.yml

**Pull request merged**
