### PR TITLE
Add advisory for iced-x86 soundness bug

### PR DESCRIPTION
**Pull request by landaire**
More information here: https://github.com/icedland/iced/issues/168

[Rendered](https://github.com/landaire/advisory-db/blob/iced-x86-advisory/crates/iced-x86/RUSTSEC-0000-0000.md).

### CODE REVIEW

**Comment by landaire** [comment]
From the CI run:

```
error: error loading advisory DB repo from .: RustSec error: parse error: error parsing ./crates/iced-x86/RUSTSEC-0000-0000.md: parse error: unexpected start of advisory: "[advisory]
id = "RUS"
Error: Process completed with exit code 1.
```

Is a newline expected at the top of the file? Otherwise it looks similar to the sample.

**Comment by Shnatsel** [comment]
Hmm, for some reason re-running the workflow installed `rustsec-admin` 0.4.2, which is gonna fail with the same error related to crates.io, so CI is gonna fail here. Weird.

**Comment by tarcieri** [comment]
@Shnatsel the CI config was changed upstream. It would need a rebase to pick up those changes.

**Comment by Shnatsel** [comment]
Cool, this broke CI in main and probably broke `cargo audit` users too :see_no_evil:

**Comment by tarcieri** [comment]
Fixing it

**Pull request merged**
