### PR TITLE
Add libp2p ed25519 signature verification failure

### PR DESCRIPTION
**Pull request by tomaka**
cc @kirushik, our infosec guy.

### CODE REVIEW

**Comment by tarcieri** [comment]
@tomaka looks like you need to rebase

**Comment by tarcieri** [comment]
Looks like the issue is filed against `libp2p-core`, but the advisory is in the `libp2p` directory

**Comment by tomaka** [comment]
Renamed!

**Comment by tarcieri** [comment]
Thanks!

**Comment by tarcieri** [comment]
Assigned RUSTSEC-2019-0004 in https://github.com/RustSec/advisory-db/pull/99

**Pull request merged**
