### PR TITLE
Request RUSTSEC for resolved UAF in OpenSSL

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by tarcieri** [comment]
This looks good but I'm going to try to address https://github.com/RustSec/rustsec-crate/issues/51 tonight. Otherwise I think this will be pretty disruptive.

**Comment by alex** [comment]
@tarcieri Is this r4r now that that's been fixed?

**Comment by tarcieri** [comment]
I need to release the `rustsec` crate, but I can do that shortly here

**Comment by tarcieri** [comment]
All right, sorry that took so long, but I think we're good to go on this now

**Comment by tarcieri** [comment]
Assigned `RUSTSEC-2018-0010` in #79

**Pull request merged**
