### PR TITLE
Anymap isn't unmaintained anymore.

### PR DESCRIPTION
**Pull request by MisileLab**
Anymap released version through https://github.com/chris-morgan/anymap/commit/2e9a570491664eea18ad61d98aa1c557d5e23e67

### CODE REVIEW

**Comment by pinkforest** [comment]
Have we tried to reach out to the maintainer or is there any type of explicit public notification that it will not be maintained anymore ?

Please see the policy:
https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md

To me it looks like @chris-morgan is the maintainer and there is no sign where the maintainer has been contacted re: status.

That has to be done and then wait 90 days unless the maintainer explicitly indicates that the crate is unmaintained.

Cheers

**Comment by pinkforest** [comment]
@chris-morgan is the maintainer I believe - it should come from the maintainer 

I don't see any comments re: maintenance in the Issues or any explicit publication re: it

Also the crate has not been updated for over five years
https://crates.io/crates/anymap

**Comment by MisileLab** [comment]
> @chris-morgan is the maintainer I believe - status update should come from the maintainer some way ..
> 
> Repo activity alone doesn't matter much -
> 
> I don't see any comments re: maintenance in the Issues or any explicit publication re: maintenance status
> 
> Also the crate has not been updated for over five years - as these are what we track [crates.io/crates/anymap](https://crates.io/crates/anymap)
> 
> Also was the withdrawal happen despite the above, we would use the `withdrawn = "YYYY-MM-DD"` field for this

[crate prerelease](https://crates.io/crates/anymap/1.0.0-beta.2) updated

**Comment by MisileLab** [comment]
I will add withdrawn section

**Comment by pinkforest** [comment]
Has the maintainer fixed the soundness issues that I believe led to people wondering about it's maintenance status ?

e.g. has it ended up into the release or will it end up into the release ?

@alexanderkjall did https://github.com/rustsec/advisory-db/pull/1099

This was the soundness issue:
https://github.com/chris-morgan/anymap/pull/32

@elichai @hellow554 were working on this:
https://github.com/chris-morgan/anymap/pull/32#issuecomment-618508620

I wonder if the maintainer intends to keep maintaining it or was this just one-off pre-release six months ago that hasn't eventuated to release .. yet perhaps ? Would like to hear from the maintainer re: intent / preferences. 

Have we raised the ticket in the repo to ask about what the maintainer's preference would be ?

**Comment by MisileLab** [comment]
I think maintainer one-time patch, not maintained. hmm, May i close pull request?

**Comment by pinkforest** [comment]
Can we try e-mailing the maintainer ? fix would be always good

**Comment by pinkforest** [comment]
And yeah I think Closed until we hear from the maintainer. Thanks for the effort though.

**Pull request closed without merging**
