### PR TITLE
Security advisory: malicious crate rustdecimal

### PR DESCRIPTION
**Pull request by Shnatsel**

### CODE REVIEW

**Comment by Shnatsel** [comment]
Ah, CI fails because this package has been permanently removed, so there's no match on crates.io for `rustdecimal`

**Comment by Shnatsel** [comment]
I've tried simply squatting it, but the name has been marked as reserved, so I cannot do that either.

**Comment by tarcieri** [comment]
@Shnatsel we'd need to add a lint skipping option to `rustsec-admin`, which wouldn't be too hard

**Comment by pinkforest** [comment]
I just added a PR for the tooling:
https://github.com/rustsec/rustsec/pull/620

Design:
https://github.com/rustsec/rustsec/issues/619

**Comment by Shnatsel** [comment]
Superseded by https://github.com/rustsec/advisory-db/pull/1312

**Pull request closed without merging**
