### PR TITLE
Advisory: hyper HTTPS MitM due to lack of hostname verification

### PR DESCRIPTION
**Pull request by tarcieri**
cc @seanmonstar

### CODE REVIEW

**Comment by tarcieri** [comment]
@seanmonstar do the contents of this advisory look correct to you?

**Comment by seanmonstar** [comment]
Hostname validation was never enabled on Windows (or enabled for 1 point version, and then disabled the next) since when enabled it couldn't validate anything. With 0.10, hyper left TLS for external libraries.

**Comment by tarcieri** [comment]
Hmm, there is currently no way to express platform-specific constraints, although that'd be a nice feature.

For now we can just add that to the description. Does that sound good?

**Comment by seanmonstar** [comment]
Sure!

**Comment by erickt** [comment]
Hello! Should this old PR be closed or merged in?

**Comment by tarcieri** [comment]
@erickt I was just looking at it! I was just updating the description to note it's Windows-only

**Comment by tarcieri** [comment]
@seanmonstar mind taking a look? probably should've asked before merging, but...

**Pull request merged**
