### PR TITLE
Yank git2 advisory; reportedly not an issue, pending further investigation

### PR DESCRIPTION
**Pull request by Shnatsel**

### CODE REVIEW

**Comment by tarcieri** [comment]
The vulnerability is embargoed, and we'll wait for the embargo to lift before taking any other public action on it

**Comment by ijackson** [comment]
For the avoidance of any doubt: I was not aware of any embargo, am not privy to any privileged sources, am "outside the tent" of any coordinated disclosure process, and have not had any private communications about this with anyone involved.

My writeup in the advisory in https://github.com/rustsec/advisory-db/pull/1518 was based on entirely public data including the public announcement of the Cargo CVE and security update point release, and the public cargo and git2-rs repositories here on github.

**Comment by pietroalbini** [comment]
As a member of the Rust Security Response WG, I want to confirm that @ijackson was not aware of any private details about any potential git2-rs or libgit2 vulnerability, nor any embargo around it, and only reconstructed the information in the advisory he posted from public sources. There hasn't been any wrongdoing on his end.

We asked the RustSec maintainers to yank this advisory because the failure to verify the SSH host keys wasn't due to git2-rs suppressing the libgit2 checks, but because [libgit2 itself didn't do any verification at all](https://github.com/libgit2/libgit2/security/advisories/GHSA-8643-3wh5-rmjq). The disclosure of the libgit2 was supposed to happen at the same time as Cargo's, but unfortunately it got delayed, creating the limbo you all saw.

**Comment by pietroalbini** [comment]
Advisory: https://github.com/rustsec/advisory-db/pull/1540

**Pull request merged**
