### PR TITLE
crates/grep-cli: add advisory for arbitrary binary execution on Windows

### PR DESCRIPTION
**Pull request by BurntSushi**
Ref https://github.com/BurntSushi/ripgrep/issues/1773

### CODE REVIEW

**Comment by Shnatsel** [comment]
Thanks for the report!

> If you use `grep-cli`'s `CommandReader` with a `std::process::Command` value on Windows, then it is recommended to either construct the `Command` with an absolute binary name, or use `grep-cli`'s new [`resolve_binary`](https://docs.rs/grep-cli/0.1.6/grep_cli/fn.resolve_binary.html) helper function.

To clarify, is the old function with the problematic behavior still accessible through the public API?

**Comment by CodesInChaos** [comment]
You forgot to fill in the title

````
> # RustSec Advisory Template - Advisory Title Goes Here
````

**Comment by BurntSushi** [comment]
@CodesInChaos Thanks, fixed!

@Shnatsel I pushed an update. Does it answer your question?

**Comment by Shnatsel** [comment]
It does. Thanks!

**Comment by CodesInChaos** [comment]
btw is there a github issue for the underlying `std::process::command` pitfall?

**Comment by BurntSushi** [comment]
@CodesInChaos No, but there should be.

**Pull request merged**
