### PR TITLE
Add unmaintained `traitobject`

### LINKED ISSUE #1088: `traitobject` is unmaintained
See: https://github.com/reem/rust-traitobject/issues/7

A maintained fork can be found at [`destructured_traitobject`](https://github.com/philip-peterson/destructure_traitobject#author).

### PR DESCRIPTION
**Pull request by pinkforest**
Fixes #1088 

Mind reviewing @ranweiler & @philip-peterson

traitobject has 8,110,280 total downloads ~7k a day..

Cheers

### CODE REVIEW

**Comment by pinkforest** [comment]
traitobject has 8,110,280 total downloads ~7k a day..

destructure_traitobject has only 200 downloads.. :(

**Comment by philip-peterson** [comment]
I'm happy to pick up the reins if people want to switch to my fork.

**Comment by philip-peterson** [comment]
Worth taking @reem as well

**Comment by pinkforest** [comment]
Some people seem to be switching to your fork anyways https://github.com/estk/log4rs/issues/247#issuecomment-1153170565

I'm figuring out if @No9 publishes fork of `typemap` and `unsafe-any` (will file a PR for this) as well

There is also another alternative for typemap which I've also raised PR: #1406

**Pull request merged**
