### PR TITLE
Add unmaintained `multi_mut`

### LINKED ISSUE #1531: `multi_mut` is unsound
https://github.com/golddranks/multi_mut has been written before Rust had an aliasing model, and before `&mut` had `noalias` annotations in LLVM. It violates Stacked Borrows and is likely UB under current LLVM behavior:

https://github.com/golddranks/multi_mut/issues/1

### PR DESCRIPTION
**Pull request by pinkforest**
Fixes #1531 

It has no dependants so I think unmaintained can do it ?

Ping: https://github.com/rust-lang/rust/issues/39155

### CODE REVIEW

**Comment by Shnatsel** [comment]
Thanks for putting this together!

I'd consider "unsound" a stronger warning than "unmaintained", so I'd prefer to go with that. "Unmaintained" was originally created for a crate with no known issues but maintainers MIA, `rustcrypto`.

Any objections? Should we update the maintainer's guide with that?

**Comment by pinkforest** [comment]
tbh we could have combined status for unmaintained and suspect unsound we can't get the maintainer input on ?

**Comment by Shnatsel** [comment]
I think an advisory without a patched version is a strong enough signal that the crate isn't maintained well.

@tarcieri thoughts?

**Comment by tarcieri** [comment]
You can file separate advisories for both issues

**Review by kornelski — APPROVED** [review]

**Pull request merged**
