### PR TITLE
rust-phonenumber: panic-on-parse

### PR DESCRIPTION
**Pull request by rubdos**
https://github.com/whisperfish/rust-phonenumber/security/advisories/GHSA-whhr-7f2w-qqj2

### CODE REVIEW

**Comment by J3rry-1729** [comment]
Hi @rubdos 

The patch is in v0.3.3+8.13.9 and v0.2.5+8.11.3 as per crates.io

image

I guess you need to update the PR as (v0.2.4 is vulnerable)

image

**Comment by rubdos** [comment]
That's a slip of the keyboard indeed, good catch and sorry for the confusion!

**Review by SteinHeselmans — APPROVED** [review]

**Comment by rubdos** [comment]
ping @Shnatsel, is there something holding this back?

**Comment by Shnatsel** [comment]
Sorry, this one fell through the cracks. I'm going to go ahead and merge it, thanks for the reminder!

**Comment by rubdos** [comment]
> Sorry, this one fell through the cracks. I'm going to go ahead and merge it, thanks for the reminder!

Thanks! #1786 probably found the same crack to fall through? :heart:

**Pull request merged**
