### PR TITLE
Add a dependabot config

### PR DESCRIPTION
**Pull request by LingMan**
Dependabot will watch the workflow files in .github/workflows and
automatically file PRs if there are updates available for any of the used
Actions.

### CODE REVIEW

**Comment by tarcieri** [comment]
Interesting. Does it pin them to hashes, or what?

**Comment by LingMan** [comment]
No, from what I've seen it updates to the latest major tag (`@v1` -> `@v3`).

**Review by pinkforest — APPROVED** [review]
I would be in favor having Dependabot :robot: bumping PR on checkout, cache and all the rest of the actions it monitors around :octocat:

**Comment by tarcieri** [comment]
It'd be really cool if it could actually pin to the latest tagged commit hash, but in the meantime this seems ok

**Comment by alex** [comment]
If you pin by hash it will send bumps to the hash. And if that hash is a
tag, it appears to only bump tags. See pyca/cryptography#7522 for example

בתאריך יום ה׳, 18 באוג׳ 2022, 9:44, מאת Tony Arcieri ‏<
***@***.***>:

**Pull request merged**
