### PR TITLE
Advisory for unsound pinning in actix-http

### PR DESCRIPTION
**Pull request by Shnatsel**

### CODE REVIEW

**Comment by Shnatsel** [comment]
Waiting on a review from Actix maintainers.

**Comment by robjtede** [comment]
LGTM

**Comment by robjtede** [comment]
Maybe I had it wrong but my comment about the date was noticing "2019" instead of "2020".

**Comment by Shnatsel** [comment]
You were right! It was me who messed up. Fixed now!

I've set the date to the day the issue was opened on the actix repo.

**Pull request merged**
