### PR TITLE
fixes #915 - remove duplicate word

### LINKED ISSUE #915: Minor typo in `RUSTSEC-2020-0027`
There is a duplicate word in https://github.com/RustSec/advisory-db/blob/main/crates/traitobject/RUSTSEC-2020-0027.md

Line 19: 
`# traitobject assumes assumes the layout of fat pointers`

Should most likely be: 
`# traitobject assumes the layout of fat pointers`

`assumes` is double.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Eh, how could this make things fail?

**Comment by Shnatsel** [comment]
I've re-run CI and it seems the error is not transient

**Comment by tarcieri** [comment]
I'm guessing this is occurring in the part of the linter that makes live requests to crates.io and ensures that the package names are correct

**Comment by Shnatsel** [comment]
I've found the culprit: https://github.com/theduke/crates_io_api/issues/30

All we have to do is upgrade `crates_io_api` dependency to 0.7.1

**Comment by alex** [comment]
Looks likes we'll need to make some time to get https://github.com/RustSec/rustsec/pull/367 green.

**Pull request merged**
