### PR TITLE
Initial advisory for owning_ref unsoundness

### PR DESCRIPTION
**Pull request by Shnatsel**
I would appreciate an opinion on whether this should be `informational = unsound` or not.

Addresses part of #1174 (the unmaintained advisory is still TODO)

### CODE REVIEW

**Comment by noamtashma** [comment]
Hi! Looks good to me.
You seem to be missing this issue: https://github.com/Kimundi/owning-ref-rs/issues/71
About an unsoundness regarding implicit constraints in the `map` functions.

**Comment by Shnatsel** [comment]
I'll see if I can get around to it. FWIW @pinkforest you should have the rights to push to this branch, it's on this repo instead of a private fork.

**Comment by pinkforest** [comment]
Thanks - Fixed it - looks good to merge :)

GH gives by default access to branches on any forks unless one ticks off "maintainer can write" .. :)

**Review by pinkforest — APPROVED** [review]

**Comment by Shnatsel** [comment]
Thanks!

**Pull request merged**
